# Generated by Django 3.1.4 on 2021-03-03 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0006_auto_20210303_2048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='des',
            new_name='blog',
        ),
    ]
