# Generated by Django 3.0.3 on 2021-04-06 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0009_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='user',
        ),
    ]
